//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopDB_W_Login.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        public int Key { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 5)]
        public string Name { get; set; }

        public string Description { get; set; }

        [Required]
        [Range(1, 100, ErrorMessage = "Please enter a quantity between 1 and 100.")]
        public Nullable<int> Quantity { get; set; }

        [DataType(DataType.Currency, ErrorMessage = "Please enter a valid currency value")]
        public Nullable<decimal> Price { get; set; }
    }
}
